version: '3.3'

services:

  postgres-auth:
    image: "postgres:10"
  postgres-user:
    image: "postgres:10"

  redis:
    image: "redis:latest"
  rabbitmq:
    image: "rabbitmq:3"

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "7000:8761"

  user-server:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-user
      - rabbitmq

  trip-server:
    build:
      context: ./trip
      dockerfile: Dockerfile
    depends_on:
      - user-server
      - eureka
      - redis
      - auth-server


  auth-server:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-auth
      - rabbitmq
      - user-server

  gateway-server:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      - redis
      - eureka
      - auth-server
      - user-server