spring:
  application:
    name: gateway-server
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user-no.westerdals.auth.service/**


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8080