server:
  port: 8087

eureka:
  instance:
    preferIpAddress: true
    hostname: gateway
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/gateway/